[platformio]
default_envs = 16_LVGL_UI
src_dir = examples/ESP-IDF/16_LVGL_UI/main

[env]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
upload_speed = 921600

; Board Hardware Configurations (ESP32-S3 16MB Flash + OPI PSRAM)
board_build.flash_size = 16MB
board_build.partitions = partitions.csv
board_upload.flash_size = 16MB
board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi

build_flags = 
    -DBOARD_HAS_PSRAM
    -Wno-error=cpp

[env:01_GPIO]

[env:02_UART]

[env:03_I2C]

[env:04_CAN]

[env:05-RS485]

[env:06_LCD]

[env:07_SD]

[env:08_Touch]

[env:09_Display_bmp]

[env:10_WIFI_SCAN]

[env:11_WIFI_STA]

[env:12_WIFI_AP]

[env:13_lvgl_v8_demo]
board_build.cmake_extra_args = 
    -DEXTRA_COMPONENT_DIRS:PATH=examples/ESP-IDF/13_lvgl_v8_demo/main;examples/ESP-IDF/16_LVGL_UI/components
    -DCONFIG_LV_USE_DEMO_WIDGETS=1
build_flags = 
    ${env.build_flags}
    -DLV_CONF_SKIP
    -DLV_USE_DEMO_WIDGETS=1
    -DLV_FONT_MONTSERRAT_14=1
    -DLV_FONT_MONTSERRAT_16=1
    -DLV_FONT_MONTSERRAT_24=1
    -DLV_FONT_MONTSERRAT_44=1

[env:14_LVGL_BTN]
board_build.cmake_extra_args = "-DEXTRA_COMPONENT_DIRS:PATH=examples/ESP-IDF/14_LVGL_BTN/main;examples/ESP-IDF/14_LVGL_BTN/components;examples/ESP-IDF/16_LVGL_UI/components"
build_flags = 
    ${env.build_flags}
    -DLV_CONF_SKIP
    -DLV_FONT_MONTSERRAT_14=1
    -DLV_FONT_MONTSERRAT_16=1
    -DLV_FONT_MONTSERRAT_24=1

[env:15_LVGL_SLIDER]
board_build.cmake_extra_args = "-DEXTRA_COMPONENT_DIRS:PATH=examples/ESP-IDF/15_LVGL_SLIDER/main;examples/ESP-IDF/15_LVGL_SLIDER/components;examples/ESP-IDF/16_LVGL_UI/components"
build_flags = 
    ${env.build_flags}
    -DLV_CONF_SKIP
    -DLV_FONT_MONTSERRAT_14=1
    -DLV_FONT_MONTSERRAT_16=1
    -DLV_FONT_MONTSERRAT_24=1

[env:16_LVGL_UI]
board_build.cmake_extra_args = "-DEXTRA_COMPONENT_DIRS:PATH=examples/ESP-IDF/16_LVGL_UI/main;examples/ESP-IDF/16_LVGL_UI/components"
build_flags = 
    ${env.build_flags}
    -DLV_CONF_SKIP
    -DLV_FONT_MONTSERRAT_14=1
    -DLV_FONT_MONTSERRAT_16=1
    -DLV_FONT_MONTSERRAT_24=1
    -DLV_FONT_MONTSERRAT_44=1

[env:17_lvgl_v9_demo]
board_build.cmake_extra_args = 
    -DEXTRA_COMPONENT_DIRS:PATH=examples/ESP-IDF/17_lvgl_v9_demo/main;examples/ESP-IDF/17_lvgl_v9_demo/components
    -DSDKCONFIG_DEFAULTS=examples/ESP-IDF/17_lvgl_v9_demo/sdkconfig.defaults
build_flags = 
    ${env.build_flags}
    -DLV_CONF_SKIP
    -DLV_USE_DEMO_WIDGETS=1
    -DLV_FONT_MONTSERRAT_14=1
    -DLV_FONT_MONTSERRAT_16=1
    -DLV_FONT_MONTSERRAT_24=1
    -DLV_FONT_MONTSERRAT_44=1
