[platformio]
src_dir = main

[env:esp32-s3-touch-lcd-7b]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf

monitor_speed = 115200
upload_speed = 921600

board_build.flash_size = 16MB
board_build.partitions = partitions.csv
board_upload.flash_size = 16MB
board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi

build_flags = 
    -DBOARD_HAS_PSRAM
    -DLV_FONT_MONTSERRAT_14=1
    -DLV_FONT_MONTSERRAT_16=1
    -DLV_FONT_MONTSERRAT_24=1

platform_packages =
    framework-espidf@symlink://C:/Users/marki/.platformio/packages/framework-espidf
    toolchain-riscv32-esp@symlink://C:/Users/marki/.platformio/packages/toolchain-riscv32-esp
    toolchain-xtensa-esp32s3@symlink://C:/Users/marki/.platformio/packages/toolchain-xtensa-esp32s3
    toolchain-xtensa-esp32@symlink://C:/Users/marki/.platformio/packages/toolchain-xtensa-esp32
    toolchain-xtensa-esp-elf@symlink://C:/Users/marki/.platformio/packages/toolchain-xtensa-esp32s3
