[platformio]
src_dir = main

[env:esp32-s3-touch-lcd-7b]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf

monitor_speed = 115200
upload_speed = 921600

; Board Hardware Configurations (ESP32-S3 16MB Flash + OPI PSRAM)
board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi

build_flags = 
    -DBOARD_HAS_PSRAM
platform_packages =
    framework-espidf@symlink://C:/Users/marki/.platformio/packages/framework-espidf
    toolchain-riscv32-esp@symlink://C:/Users/marki/.platformio/packages/toolchain-riscv32-esp
    toolchain-xtensa-esp32s3@symlink://C:/Users/marki/.platformio/packages/toolchain-xtensa-esp32s3
    toolchain-xtensa-esp32@symlink://C:/Users/marki/.platformio/packages/toolchain-xtensa-esp32
    toolchain-xtensa-esp-elf@symlink://C:/Users/marki/.platformio/packages/toolchain-xtensa-esp32s3
